const donatorsList = [
    "SkyStep",
    "qqwref",
    "c0wmanglr",
    "goodevening",
    "XLII",
    "VanillaGawr",
    "Blueoanaoa",
    "OCEshadow",
    "iota",
    "MOKA",
    "xsedim"
];

const adminsList = [
    "dphdmn",
    "vovker",
    "daanbe",
    "ivy"
];

const rename_map = {
    'ivy': 'daanbe',
    'skye': 'iota',
    'eggben': 'ben1996123',
    'eskiu': 'sq',
    'HashPanda': 'Rafael',
    'wiser': 'wiserboblouis',
    'garyx': 'gr21xx',
    'ekimmy': 'ekim',
    'ap_web': 'ap',
    'juunas': 'asdfghqwerty',
    'minsie': 'MegaminX',
    '554': 'yzx',
    'JonasCuber10': 'JonasCuber11',
    'DreamerTheWolfFox': 'Dreamer'
};

function appendFlagIconToNickname(nickname, minimal = false) {
    const lowerCaseNickname = nickname.toLowerCase();
    let country = null;

    for (const user in userCountryMap) {
        if (user.toLowerCase() === lowerCaseNickname) {
            country = userCountryMap[user];
            break;
        }
    }

    const flagIconLink = country && countryEmojis[country]
        ? countryEmojis[country]
        : "images/flags/default.png";

    const isDonator = donatorsList.some(donator => donator.toLowerCase() === lowerCaseNickname);

    const donatorIcon = isDonator
        ? `<span class="gold-icon-link"><img class="emoji" draggable="false" alt="gold" src="images/gold.png" style="border-radius:50%"></span>`
        : '';

    const isAdminOrDeveloper = adminsList.some(user => user.toLowerCase() === lowerCaseNickname);

    const roleIcon = isAdminOrDeveloper
        ? `<span class="admin-icon-link">🛠️</span>`
        : '';

    return `<img class="emoji" draggable="false" alt="${country || 'unknown'}" src="${flagIconLink}">${nickname}${roleIcon}${donatorIcon}`;
}

//countries list and emoji for users to add flags

let userCountryMap = {
    Australia: 'Australia',
    Belarus: 'Belarus',
    Belgium: 'Belgium',
    Bulgaria: 'Bulgaria',
    Canada: 'Canada',
    China: 'China',
    Colombia: 'Colombia',
    'Czech Republic': 'Czech Republic',
    Finland: 'Finland',
    France: 'France',
    Germany: 'Germany',
    'Hong Kong': 'Hong Kong',
    India: 'India',
    Italy: 'Italy',
    Malaysia: 'Malaysia',
    Mexico: 'Mexico',
    Netherlands: 'Netherlands',
    Philippines: 'Philippines',
    Poland: 'Poland',
    Russia: 'Russia',
    Serbia: 'Serbia',
    Singapore: 'Singapore',
    Taiwan: 'Taiwan',
    UK: 'UK',
    Japan: 'Japan',
    Ukraine: 'Ukraine',
    USA: 'USA',
    Brazil: 'Brazil',
    Norway: 'Norway',
    'New Zealand': 'New Zealand',
    Indonesia: 'Indonesia',
    Vietnam: 'Vietnam',
    Iceland: 'Iceland',
    Scotland: 'Scotland',
    Slovenia: 'Slovenia',
    'South Africa': 'South Africa',
    Sweden: 'Sweden',
    Afghanistan: 'Afghanistan',

    kaxymonoxy: 'Iceland',

    Tronamo: 'Australia',
    Brendan7625: 'Australia',
    lekh2003: 'Australia',
    OCEshadow: 'Australia',
    boink: 'Australia',
    TOOFAST: 'Australia',
    wiserboblouis: 'Australia',
    macandcheese: 'Australia',
    Ton618: 'Australia',
    retsni: 'Australia',
    TeamMathcraft: 'Australia',
    VCP29: 'Australia',
  
    Utochka: 'Belarus',
  
    larsvdb97: 'Belgium',
  
    luybo: 'Bulgaria',
    'v_perm': 'Bulgaria',
    qwerty6450: 'Bulgaria',
    omgplayer: 'Bulgaria',
  
    ap: 'Canada',
    vcuber13: 'Canada',
    yoshinator879: 'Canada',
    Arm0nd0: 'Canada',
    frederick: 'Canada',
  
    Blueoanaoa: 'China',
    JZE: 'China',
    diudiuhamburger: 'China',
    gwj: 'China',
    XMeng: 'China',
    zyc: 'China',
    Ruan: 'China',
    yzx: 'China',
    chy: 'China',
    mochuannnn: 'China',
    '0jacky0': 'China',
    '13975': 'China',
    lzy: 'China',
    lulu: 'China',
    CYY: 'China',
  
    Luisa15: 'Colombia',
    chaeerin: 'Colombia',
  
    Lunarien: 'Czech Republic',
    wrist: 'Czech Republic',
    RZBAKA: 'Czech Republic',
    OgYardel: 'Czech Republic',
  
    asdfghqwerty: 'Finland',
  
    sq: 'France',
    Nikokas: 'France',
    Ladoly: 'France',
    Asbjorn: 'France',
    Netamma: 'France',
    kolunoa: 'France',
    Sarenard: 'France',
    bambinex: 'France',
  
    daanbe: 'Germany',
    XLII: 'Germany',
    dyslexus: 'Germany',
    RedstoneTim: 'Germany',
    Corpllwacquirerrichmf: 'Germany',
    Zip: 'Germany',
    JonasCuber11: 'Germany',
    dani2: 'Germany',
    HawaiiBlue: 'Germany',
    fuenfeck: 'Germany',
  
    Rouxles: 'Hong Kong',
  
    HackerTyper492: 'India',
    krjjod: 'India',
  
    imvelox: 'Italy',
    Nabbissimux: 'Italy',
    DedolCubing: 'Italy',
    chettocri: 'Italy',
    ebrancati: 'Italy',
  
    thelegendary08: 'Malaysia',
  
    gottagitgud: 'Mexico',
  
    Rafael: 'Netherlands',
    JihadCubing: 'Netherlands',
    winteriscool: 'Netherlands',
  
    eff: 'Philippines',
    Enzo1098: 'Philippines',
    usernameh1h2: 'Philippines',
    Nyajumi: 'Philippines',
  
    Dawidluna: 'Poland',
    kiraa96: 'Poland',
    pankubix: 'Poland',
    Verscup: 'Poland',
    Kingstone: 'Poland',
    Dekodzi: 'Poland',
    erykkas: 'Poland',
    bibi100101: 'Poland',
  
    dphdmn: 'Russia',
    vovker: 'Russia',
    goodevening: 'Russia',
    quing: 'Russia',
    OsipovAleksander: 'Russia',
    GoldenBoy: 'Russia',
    IslamKitiev: 'Russia',
    Wrabbable: 'Russia',
    kv1nk: 'Russia',
    gontod195: 'Russia',
    YanikusGG: 'Russia',
    Antonyme: 'Russia',
    thetskerp: 'Russia',
    VyacheslavPervushin: 'Russia',
    vedroboev: 'Russia',
    dima: 'Russia',
    '1210': 'Russia',
    VanillaGawr: 'Russia',
    moceke: 'Russia',
    vmejion: 'Russia',
  
    jug: 'Serbia',
    andrewtheslider: 'Serbia',
  
    peaceknight05: 'Singapore',
    BollnKK: 'Singapore',
    allenbot: 'Singapore',
    MegaminX: 'Singapore',

    gr21xx: 'Slovenia',
  
    SunOceanBeach: 'Taiwan',
  
    ben1996123: 'UK',
    Tree: 'UK',
    TDM: 'UK',
    Billabob: 'UK',
    sameer: 'UK',
    chbld: 'UK',
    JL586: 'UK',
    Garfologist: 'UK',
    darkanturian: 'UK',
    billzo: 'UK',
    Shadowslice: 'UK',
    Berkmann18: 'UK',
    sam596: 'UK',
    luca: 'UK',
    iota: 'UK',
    Waldi: 'UK',
    '2017HARR08': 'UK',
  
    HoHo: 'Japan',
    Ncuber: 'Japan',
  
    IgorTarasov: 'Ukraine',
    oliynykmax: 'Ukraine',
    faugore: 'Ukraine',
    Notobiv: 'Ukraine',
  
    man142: 'USA',
    Magentawolf27YT: 'USA',
    R14: 'USA',
    xsedim: 'USA',
    TheMatsValk: 'USA',
    tnum10: 'USA',
    SkyStep: 'USA',
    soup: 'USA',
    Scyter: 'USA',
    enigma515: 'USA',
    qqwref: 'USA',
    upvoid: 'USA',
    happydays: 'USA',
    LEBaldy: 'USA',
    strakerak: 'USA',
    c0wmanglr: 'USA',
    mAyo: 'USA',
    teri: 'USA',
    ShyGuy1265: 'USA',
    creepycat18: 'USA',
    Ianwubby: 'USA',
    BindeDSA: 'USA',
    Sethamajig: 'USA',
    MLGSheep1: 'USA',
    BrickInAPresent: 'USA',
    Owen: 'USA',
    Dapianokid: 'USA',
    Dreamer: 'USA',
    '105iqengineer': 'USA',
    Alex: 'USA',
    alka: 'USA',
    kleb: 'USA',
    HOGGYSIMP: 'USA',
    amazingpikachu37: 'USA',
    zach: 'USA',
    July2nd: 'USA',
    robotmania: 'USA',
    Alumina: 'USA',
    Spliffey: 'USA',
    zander: 'USA',
    xishu: 'USA',
    justnnotyou: 'USA',
    BrethrenBeef: 'USA',
    MOKA: 'USA',
    theepossum: 'USA',
    ryan5: 'USA',
    WillTRM: 'USA',
    clementinebedsheets: 'USA',
    lopsidedhampter: 'USA',
    '2023RAMA09': 'USA',
    Chanoh17: 'USA',
  
    Sakinuto: 'Brazil',
    PedroAM: 'Brazil',
  
    Yiclaw: 'Norway',
  
    majesticwalrus: 'New Zealand',
  
    Berries1111: 'Indonesia',
  
    hkg11khanh: 'Vietnam',
    Duysen: 'Vietnam',
    nguywn: 'Vietnam',

    zynua: 'South Africa',
    Yokow: 'South Africa',

    xenia: 'Sweden',
    Andersh2345: 'Sweden',

    TheGameChallenger: 'Afghanistan'

  };

  

const countryEmojis = {
    Indonesia: 'images/flags/Indonesia.png',
    Australia: 'images/flags/Australia.png',
    Belarus: 'images/flags/Belarus.png',
    Belgium: 'images/flags/Belgium.png',
    Bulgaria: 'images/flags/Bulgaria.png',
    Canada: 'images/flags/Canada.png',
    China: 'images/flags/China.png',
    Colombia: 'images/flags/Colombia.png',
    'Czech Republic': 'images/flags/Czech-Republic.png',
    Finland: 'images/flags/Finland.png',
    France: 'images/flags/France.png',
    Germany: 'images/flags/Germany.png',
    'Hong Kong': 'images/flags/Hong-Kong.png',
    India: 'images/flags/India.png',
    Italy: 'images/flags/Italy.png',
    Malaysia: 'images/flags/Malaysia.png',
    Mexico: 'images/flags/Mexico.png',
    Netherlands: 'images/flags/Netherlands.png',
    Philippines: 'images/flags/Philippines.png',
    Poland: 'images/flags/Poland.png',
    Russia: 'images/flags/Russia.png',
    Serbia: 'images/flags/Serbia.png',
    Singapore: 'images/flags/Singapore.png',
    Taiwan: 'images/flags/Taiwan.png',
    'UK': 'images/flags/United-Kingdom.png',
    Japan: 'images/flags/Japan.png',
    Ukraine: 'images/flags/Ukraine.png',
    'USA': 'images/flags/United-States.png',
    Brazil: 'images/flags/Brazil.png',
    Norway: 'images/flags/Norway.png',
    'New Zealand': 'images/flags/New-Zealand.png',
    Vietnam: 'images/flags/Vietnam.png',
    Abkhazia: 'images/flags/Abkhazia.png',
    Afghanistan: 'images/flags/Afghanistan.png',
    Aland: 'images/flags/Aland.png',
    Albania: 'images/flags/Albania.png',
    Algeria: 'images/flags/Algeria.png',
    'American Samoa': 'images/flags/American-Samoa.png',
    Andorra: 'images/flags/Andorra.png',
    Angola: 'images/flags/Angola.png',
    Anguilla: 'images/flags/Anguilla.png',
    Antarctica: 'images/flags/Antarctica.png',
    'Antigua and Barbuda': 'images/flags/Antigua-and-Barbuda.png',
    Argentina: 'images/flags/Argentina.png',
    Armenia: 'images/flags/Armenia.png',
    Aruba: 'images/flags/Aruba.png',
    Australia: 'images/flags/Australia.png',
    Austria: 'images/flags/Austria.png',
    Azerbaijan: 'images/flags/Azerbaijan.png',
    Bahamas: 'images/flags/Bahamas.png',
    Bahrain: 'images/flags/Bahrain.png',
    Bangladesh: 'images/flags/Bangladesh.png',
    Barbados: 'images/flags/Barbados.png',
    'Basque Country': 'images/flags/Basque-Country.png',
    Belarus: 'images/flags/Belarus.png',
    Belgium: 'images/flags/Belgium.png',
    Belize: 'images/flags/Belize.png',
    Benin: 'images/flags/Benin.png',
    Bermuda: 'images/flags/Bermuda.png',
    Bhutan: 'images/flags/Bhutan.png',
    Bolivia: 'images/flags/Bolivia.png',
    'Bosnia and Herzegovina': 'images/flags/Bosnia-and-Herzegovina.png',
    Botswana: 'images/flags/Botswana.png',
    Brazil: 'images/flags/Brazil.png',
    'British Antarctic Territory': 'images/flags/British-Antarctic-Territory.png',
    'British Virgin Islands': 'images/flags/British-Virgin-Islands.png',
    Brunei: 'images/flags/Brunei.png',
    Bulgaria: 'images/flags/Bulgaria.png',
    'Burkina Faso': 'images/flags/Burkina-Faso.png',
    Burundi: 'images/flags/Burundi.png',
    Cambodia: 'images/flags/Cambodia.png',
    Cameroon: 'images/flags/Cameroon.png',
    Canada: 'images/flags/Canada.png',
    'Canary Islands': 'images/flags/Canary-Islands.png',
    'Cape Verde': 'images/flags/Cape-Verde.png',
    'Cayman Islands': 'images/flags/Cayman-Islands.png',
    'Central African Republic': 'images/flags/Central-African-Republic.png',
    Chad: 'images/flags/Chad.png',
    Chile: 'images/flags/Chile.png',
    China: 'images/flags/China.png',
    'Christmas Island': 'images/flags/Christmas-Island.png',
    'Cocos Keeling Islands': 'images/flags/Cocos-Keeling-Islands.png',
    Colombia: 'images/flags/Colombia.png',
    Commonwealth: 'images/flags/Commonwealth.png',
    Comoros: 'images/flags/Comoros.png',
    'Cook Islands': 'images/flags/Cook-Islands.png',
    'Costa Rica': 'images/flags/Costa-Rica.png',
    "Cote d'Ivoire": 'images/flags/Cote-dIvoire.png',
    Croatia: 'images/flags/Croatia.png',
    Cuba: 'images/flags/Cuba.png',
    Curacao: 'images/flags/Curacao.png',
    Cyprus: 'images/flags/Cyprus.png',
    'Czech Republic': 'images/flags/Czech-Republic.png',
    'Democratic Republic of the Congo': 'images/flags/Democratic-Republic-of-the-Congo.png',
    Denmark: 'images/flags/Denmark.png',
    Djibouti: 'images/flags/Djibouti.png',
    Dominica: 'images/flags/Dominica.png',
    'Dominican Republic': 'images/flags/Dominican-Republic.png',
    'East Timor': 'images/flags/East-Timor.png',
    Ecuador: 'images/flags/Ecuador.png',
    Egypt: 'images/flags/Egypt.png',
    'El Salvador': 'images/flags/El-Salvador.png',
    England: 'images/flags/England.png',
    'Equatorial Guinea': 'images/flags/Equatorial-Guinea.png',
    Eritrea: 'images/flags/Eritrea.png',
    Estonia: 'images/flags/Estonia.png',
    Ethiopia: 'images/flags/Ethiopia.png',
    'European Union': 'images/flags/European-Union.png',
    'Falkland Islands': 'images/flags/Falkland-Islands.png',
    Faroes: 'images/flags/Faroes.png',
    Fiji: 'images/flags/Fiji.png',
    Finland: 'images/flags/Finland.png',
    France: 'images/flags/France.png',
    'French Polynesia': 'images/flags/French-Polynesia.png',
    'French Southern Territories': 'images/flags/French-Southern-Territories.png',
    Gabon: 'images/flags/Gabon.png',
    Gambia: 'images/flags/Gambia.png',
    Georgia: 'images/flags/Georgia.png',
    Germany: 'images/flags/Germany.png',
    Ghana: 'images/flags/Ghana.png',
    Gibraltar: 'images/flags/Gibraltar.png',
    GoSquared: 'images/flags/GoSquared.png',
    Greece: 'images/flags/Greece.png',
    Greenland: 'images/flags/Greenland.png',
    Grenada: 'images/flags/Grenada.png',
    Guam: 'images/flags/Guam.png',
    Guatemala: 'images/flags/Guatemala.png',
    Guernsey: 'images/flags/Guernsey.png',
    'Guinea Bissau': 'images/flags/Guinea-Bissau.png',
    Guinea: 'images/flags/Guinea.png',
    Guyana: 'images/flags/Guyana.png',
    Haiti: 'images/flags/Haiti.png',
    Honduras: 'images/flags/Honduras.png',
    'Hong Kong': 'images/flags/Hong-Kong.png',
    Hungary: 'images/flags/Hungary.png',
    Iceland: 'images/flags/Iceland.png',
    India: 'images/flags/India.png',
    Indonesia: 'images/flags/Indonesia.png',
    Iran: 'images/flags/Iran.png',
    Iraq: 'images/flags/Iraq.png',
    Ireland: 'images/flags/Ireland.png',
    'Isle of Man': 'images/flags/Isle-of-Man.png',
    Israel: 'images/flags/Israel.png',
    Italy: 'images/flags/Italy.png',
    Jamaica: 'images/flags/Jamaica.png',
    Japan: 'images/flags/Japan.png',
    Jersey: 'images/flags/Jersey.png',
    Jordan: 'images/flags/Jordan.png',
    Kazakhstan: 'images/flags/Kazakhstan.png',
    Kenya: 'images/flags/Kenya.png',
    Kiribati: 'images/flags/Kiribati.png',
    Kosovo: 'images/flags/Kosovo.png',
    Kuwait: 'images/flags/Kuwait.png',
    Kyrgyzstan: 'images/flags/Kyrgyzstan.png',
    Laos: 'images/flags/Laos.png',
    Latvia: 'images/flags/Latvia.png',
    Lebanon: 'images/flags/Lebanon.png',
    Lesotho: 'images/flags/Lesotho.png',
    Liberia: 'images/flags/Liberia.png',
    Libya: 'images/flags/Libya.png',
    Liechtenstein: 'images/flags/Liechtenstein.png',
    Lithuania: 'images/flags/Lithuania.png',
    Luxembourg: 'images/flags/Luxembourg.png',
    Macau: 'images/flags/Macau.png',
    Macedonia: 'images/flags/Macedonia.png',
    Madagascar: 'images/flags/Madagascar.png',
    Malawi: 'images/flags/Malawi.png',
    Malaysia: 'images/flags/Malaysia.png',
    Maldives: 'images/flags/Maldives.png',
    Mali: 'images/flags/Mali.png',
    Malta: 'images/flags/Malta.png',
    Mars: 'images/flags/Mars.png',
    'Marshall Islands': 'images/flags/Marshall-Islands.png',
    Martinique: 'images/flags/Martinique.png',
    Mauritania: 'images/flags/Mauritania.png',
    Mauritius: 'images/flags/Mauritius.png',
    Mayotte: 'images/flags/Mayotte.png',
    Mexico: 'images/flags/Mexico.png',
    Micronesia: 'images/flags/Micronesia.png',
    Moldova: 'images/flags/Moldova.png',
    Monaco: 'images/flags/Monaco.png',
    Mongolia: 'images/flags/Mongolia.png',
    Montenegro: 'images/flags/Montenegro.png',
    Montserrat: 'images/flags/Montserrat.png',
    Morocco: 'images/flags/Morocco.png',
    Mozambique: 'images/flags/Mozambique.png',
    Myanmar: 'images/flags/Myanmar.png',
    'Nagorno Karabakh': 'images/flags/Nagorno-Karabakh.png',
    Namibia: 'images/flags/Namibia.png',
    NATO: 'images/flags/NATO.png',
    Nauru: 'images/flags/Nauru.png',
    Nepal: 'images/flags/Nepal.png',
    'Netherlands Antilles': 'images/flags/Netherlands-Antilles.png',
    Netherlands: 'images/flags/Netherlands.png',
    'New Caledonia': 'images/flags/New-Caledonia.png',
    'New Zealand': 'images/flags/New-Zealand.png',
    Nicaragua: 'images/flags/Nicaragua.png',
    Niger: 'images/flags/Niger.png',
    Nigeria: 'images/flags/Nigeria.png',
    Niue: 'images/flags/Niue.png',
    'Norfolk Island': 'images/flags/Norfolk-Island.png',
    'North Korea': 'images/flags/North-Korea.png',
    'Northern Cyprus': 'images/flags/Northern-Cyprus.png',
    'Northern Mariana Islands': 'images/flags/Northern-Mariana-Islands.png',
    Norway: 'images/flags/Norway.png',
    Olympics: 'images/flags/Olympics.png',
    Oman: 'images/flags/Oman.png',
    Pakistan: 'images/flags/Pakistan.png',
    Palau: 'images/flags/Palau.png',
    Palestine: 'images/flags/Palestine.png',
    Panama: 'images/flags/Panama.png',
    'Papua New Guinea': 'images/flags/Papua-New-Guinea.png',
    Paraguay: 'images/flags/Paraguay.png',
    Peru: 'images/flags/Peru.png',
    Philippines: 'images/flags/Philippines.png',
    'Pitcairn Islands': 'images/flags/Pitcairn-Islands.png',
    Poland: 'images/flags/Poland.png',
    Portugal: 'images/flags/Portugal.png',
    'Puerto Rico': 'images/flags/Puerto-Rico.png',
    Qatar: 'images/flags/Qatar.png',
    'Red Cross': 'images/flags/Red-Cross.png',
    'Republic of the Congo': 'images/flags/Republic-of-the-Congo.png',
    Romania: 'images/flags/Romania.png',
    Russia: 'images/flags/Russia.png',
    Rwanda: 'images/flags/Rwanda.png',
    'Saint Barthelemy': 'images/flags/Saint-Barthelemy.png',
    'Saint Helena': 'images/flags/Saint-Helena.png',
    'Saint Kitts and Nevis': 'images/flags/Saint-Kitts-and-Nevis.png',
    'Saint Lucia': 'images/flags/Saint-Lucia.png',
    'Saint Martin': 'images/flags/Saint-Martin.png',
    'Saint Vincent and the Grenadines': 'images/flags/Saint-Vincent-and-the-Grenadines.png',
    Samoa: 'images/flags/Samoa.png',
    'San Marino': 'images/flags/San-Marino.png',
    'Sao Tome and Principe': 'images/flags/Sao-Tome-and-Principe.png',
    'Saudi Arabia': 'images/flags/Saudi-Arabia.png',
    Scotland: 'images/flags/Scotland.png',
    Senegal: 'images/flags/Senegal.png',
    Serbia: 'images/flags/Serbia.png',
    Seychelles: 'images/flags/Seychelles.png',
    'Sierra Leone': 'images/flags/Sierra-Leone.png',
    Singapore: 'images/flags/Singapore.png',
    Slovakia: 'images/flags/Slovakia.png',
    Slovenia: 'images/flags/Slovenia.png',
    'Solomon Islands': 'images/flags/Solomon-Islands.png',
    Somalia: 'images/flags/Somalia.png',
    Somaliland: 'images/flags/Somaliland.png',
    'South Africa': 'images/flags/South-Africa.png',
    'South Georgia and the South Sandwich Islands': 'images/flags/South-Georgia-and-the-South-Sandwich-Islands.png',
    'South Korea': 'images/flags/South-Korea.png',
    'South Ossetia': 'images/flags/South-Ossetia.png',
    'South Sudan': 'images/flags/South-Sudan.png',
    Spain: 'images/flags/Spain.png',
    'Sri Lanka': 'images/flags/Sri-Lanka.png',
    Sudan: 'images/flags/Sudan.png',
    Suriname: 'images/flags/Suriname.png',
    Swaziland: 'images/flags/Swaziland.png',
    Sweden: 'images/flags/Sweden.png',
    Switzerland: 'images/flags/Switzerland.png',
    Syria: 'images/flags/Syria.png',
    Taiwan: 'images/flags/Taiwan.png',
    Tajikistan: 'images/flags/Tajikistan.png',
    Tanzania: 'images/flags/Tanzania.png',
    Thailand: 'images/flags/Thailand.png',
    Togo: 'images/flags/Togo.png',
    Tokelau: 'images/flags/Tokelau.png',
    Tonga: 'images/flags/Tonga.png',
    'Trinidad and Tobago': 'images/flags/Trinidad-and-Tobago.png',
    Tunisia: 'images/flags/Tunisia.png',
    Turkey: 'images/flags/Turkey.png',
    Turkmenistan: 'images/flags/Turkmenistan.png',
    'Turks and Caicos Islands': 'images/flags/Turks-and-Caicos-Islands.png',
    Tuvalu: 'images/flags/Tuvalu.png',
    Uganda: 'images/flags/Uganda.png',
    Ukraine: 'images/flags/Ukraine.png',
    'United Arab Emirates': 'images/flags/United-Arab-Emirates.png',
    'United Kingdom': 'images/flags/United-Kingdom.png',
    'United Nations': 'images/flags/United-Nations.png',
    'United States': 'images/flags/United-States.png',
    Unknown: 'images/flags/Unknown.png',
    Uruguay: 'images/flags/Uruguay.png',
    'US Virgin Islands': 'images/flags/US-Virgin-Islands.png',
    Uzbekistan: 'images/flags/Uzbekistan.png',
    Vanuatu: 'images/flags/Vanuatu.png',
    'Vatican City': 'images/flags/Vatican-City.png',
    Venezuela: 'images/flags/Venezuela.png',
    Vietnam: 'images/flags/Vietnam.png',
    Wales: 'images/flags/Wales.png',
    'Wallis And Futuna': 'images/flags/Wallis-And-Futuna.png',
    'Western Sahara': 'images/flags/Western-Sahara.png',
    Yemen: 'images/flags/Yemen.png',
    Zambia: 'images/flags/Zambia.png',
    Zimbabwe: 'images/flags/Zimbabwe.png',
    cheat: 'images/flags/cheat.png'
};

// Update keys using rename_map (old names -> new names)
for (const username of Object.keys(userCountryMap)) {
    // Find if this username is an old name in rename_map
    for (const [newName, oldName] of Object.entries(rename_map)) {
        if (oldName === username) {
            const country = userCountryMap[username];
            delete userCountryMap[username];
            userCountryMap[newName] = country;
            break;
        }
    }
}

// Update donatorsList using rename_map (old names -> new names)
for (let i = 0; i < donatorsList.length; i++) {
    for (const [newName, oldName] of Object.entries(rename_map)) {
        if (oldName === donatorsList[i]) {
            donatorsList[i] = newName;
            break;
        }
    }
}